services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: temperinho
      POSTGRES_USER: temperinho
      POSTGRES_PASSWORD: temperinho
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:v1.10
    environment:
      MEILI_MASTER_KEY: masterKey
    ports:
      - "7700:7700"
    volumes:
      - meilidata:/meili_data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file: ./apps/api/.env
    ports:
      - "8000:9000"
    depends_on:
      - postgres
      - redis
      - meilisearch
    volumes:
      - ./apps/api:/var/www

  front:
    build:
      context: ./apps/front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file: ./apps/front/.env.local
    depends_on:
      - api
    volumes:
      - ./apps/front:/app
      - /app/node_modules

  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file: ./apps/admin/.env.local
    depends_on:
      - api
    volumes:
      - ./apps/admin:/app
      - /app/node_modules

volumes:
  pgdata:
  meilidata:
