server {
    listen 80 default_server;

    root /var/www/public;
    index index.php;
    charset utf-8;

    access_log /var/log/nginx/temperinho-api.access.log;
    error_log  /var/log/nginx/temperinho-api.error.log warn;

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=100r/m;
    limit_req_status 429;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        limit_req zone=api_limit burst=20 nodelay;
    }

    location ~ /\.(?!well-known).* {
        deny all;
        access_log off;
        log_not_found off;
    }

    location ~ \.php$ {
        fastcgi_pass api:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_buffer_size 128k;
        fastcgi_buffers 4 256k;
        fastcgi_busy_buffers_size 256k;

        limit_req zone=api_limit burst=20 nodelay;
    }
}